name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Altere para 'master' se esse for o seu branch principal

# Adicione esta seção de permissões no nível superior do workflow
permissions:
  contents: read # Permite ler o conteúdo do repositório
  pages: write # Permite que a ação escreva no GitHub Pages
  id-token: write # Permite que a ação gere um token OIDC para autenticação

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use uma versão LTS do Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm npm run build

      - name: Upload Pages artifact
        # Esta etapa faz o upload da sua pasta 'out' como um artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # O caminho para a sua pasta de build estático do Next.js

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Garante que o job de deploy só rode depois que o build for concluído
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # Esta etapa implanta o artefato que foi feito upload no job 'build'
        uses: actions/deploy-pages@v4
